version: '3.6'

services:
    db:
        image: mysql:5.7
        container_name: web-phala-miner-monitor-db
        user: "1000:1000"
        restart: "no"
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=$DB_NAME
            - MYSQL_USER=$DB_USER
            - MYSQL_PASSWORD=$DB_PASSWORD
            - TZ=Europe/Warsaw
        ports:
            - 3306:3306
        volumes:
            - ./.db-data:/var/lib/mysql
            - ./etc/mysql.conf.d:/etc/mysql/conf.d
    dba:
        image: phpmyadmin:5
        container_name: web-phala-miner-monitor-dba
        links:
            - db
        ports:
            - 19036:80
        environment:
            PMA_HOST: db
            PMA_PASSWORD: db
            PMA_USER: db
        restart: "always"
        volumes:
            - ./etc/pma/config.header.inc.php:/etc/phpmyadmin/config.header.inc.php:rw
            - ./etc/pma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:rw
